### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lvivua032** [keithorange/PsychicTrader#1]
**from quantum_random import QuantumRandom
ModuleNotFoundError: No module named 'quantum_random'**

 pip install quantum_random
Requirement already satisfied: quantum_random in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (1.3.2)
Requirement already satisfied: requests in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (from quantum_random) (2.28.2)
Requirement already satisfied: xdg in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (from quantum_random) (6.0.0)
Requirement already satisfied: typing-extensions in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (from quantum_random) (4.7.1)
Requirement already satisfied: click in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (from quantum_random) (8.1.6)
Requirement already satisfied: colorama in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (from click->quantum_random) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (from requests->quantum_random) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (from requests->quantum_random) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (from requests->quantum_random) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\andrii\appdata\local\programs\python\python311\lib\site-packages (from requests->quantum_random) (2023.7.22)****

**Comment by keithorange** [comment]
you can use the quantum random number generator at https://github.com/keithorange/HotBits or just use `import random`
